### PR TITLE
Provide configuration for all currently available targets

### LINKED ISSUE #23: ESP32-C6 Support
The library currently fails to compile for the ESP32-C6 target. Part of it seems to be the missing declaration of `INVALID_GPIOS`, but it looks like there's also something about the number of I2C that needs adjustment.

### PR DESCRIPTION
**Pull request by 0xjakob**
This MR adds example configurations for all currently available targets. Before, builds would fail on some targets due to these missing configurations.

This MR also fixes a wrong link in the documentation.

closes #23

### CODE REVIEW

**Review by yves72 — COMMENTED** [review]
I'm currently developing with the C6 variant and i am missing the changes that are in these commits. I would love to use the c++ libary without using custom components.

Thanks.

**Comment by 0xjakob** [comment]
@yves72 Sorry for the long delay. We'll merge this ASAP. Just need an approval.

**Review by igrr — APPROVED** [review]
Haven't checked all the pin numbers, but LGTM!

File: examples/simple_spi_rw_example/main/simple_spi_rw_example.cpp [hunk 1]
```diff
@@ -12,38 +12,36 @@
...
+static const MOSI MOSI_PIN(CONFIG_SPI_MOSI);
+static const MISO MISO_PIN(CONFIG_SPI_MISO);
+static const SCLK SCLK_PIN(CONFIG_SPI_SCLK);
+static const CS     CS_PIN(CONFIG_SPI_CS);
+}
+
 extern "C" void app_main(void)
 {
-    try {
+        SPIMaster master(SPINum(1),
```
Comment (igrr) [inline examples/simple_spi_rw_example/main/simple_spi_rw_example.cpp:34]: Nitpick: since try/catch is removed, this block can now be moved left by 4 spaces

**Comment by 0xjakob** [comment]
@yves72 We've merged this PR. Please let us know if you still encounter any problems with C6.

@igrr I've manually checked all the pin configurations when creating this PR.

**Comment by JesperBellenbaum** [comment]
Hi there,

I'd call myself an esp-beginner so this might be just a setup error on my side but when I try to run the example **simple_i2c_rw_example** , I get:

`espressif__esp-idf-cxx/i2c_cxx.cpp:22:15: error: 'I2C_NUM_1' was not declared in this scope; did you mean 'I2C_NUM_0'?
   22 | static_assert(I2C_NUM_1 == 1, "I2C_NUM_1 must be equal to 1");
      |               ^~~~~~~~~
      |               I2C_NUM_0`
      
image

Any help appreciated!

**Comment by TreesAreOP** [comment]
> Hi there,
> 
> I'd call myself an esp-beginner so this might be just a setup error on my side but when I try to run the example **simple_i2c_rw_example** , I get:
> 
> `espressif__esp-idf-cxx/i2c_cxx.cpp:22:15: error: 'I2C_NUM_1' was not declared in this scope; did you mean 'I2C_NUM_0'? 22 | static_assert(I2C_NUM_1 == 1, "I2C_NUM_1 must be equal to 1"); | ^~~~~~~~~ | I2C_NUM_0`
> 
> image
> Any help appreciated!

Same for me on the C6.
